### ISSUE TITLE
Two issue about interface layout and file sorting methods

### ISSUE THREAD

**Issue by mkzpd** [ShokhrukhbekYuldoshev/Meloplay#1]
Hi, I am using the app that written by you, I think it's good, thank you for work. Sorry for English is not my mother tongue.

In the process of using it, I've noticed a few areas that could potentially be improved for better functionality.

# First issue 

First, let's address the issue regarding the interface.

When I click "Albums", then click "English Grammar in Use", see below picture we call it Figure-1:

![Figure-1](https://github.com/ShokhrukhbekYuldoshev/Meloplay/assets/50985604/46d83123-70dc-409d-a5d9-96f173eed698)

I go to below interface , below picture we call it Figure-2:

![Figure-2](https://github.com/ShokhrukhbekYuldoshev/Meloplay/assets/50985604/4d077759-cb29-42bf-a110-3b3f981721dd)

I personally think that in Figure-2 the green-highlighted portion above is redundant. It occupies almost half of the entire screen, severely affecting the visibility of the MP3 playlist. Additionally, as shown in the above image Figure-2, you can't see "100A" on the interface, In the local file manager of my phone, I do have this file indeed, please see below picture we call it Figure-3. 

![Figure-3](https://github.com/ShokhrukhbekYuldoshev/Meloplay/assets/50985604/a7687329-b87c-49e7-b61a-8ea6dae77dba)

I speculate that it might be located where the red circle is in the image Figure-2, but my viewpoint may not be accurate, just a guess. I feel that this interface needs modification, and you can refer to above the image  Figure-3 for guidance.

The first area that needs modification is: simply put, it's about removing the green-highlighted portion circled in Figure-2, and instead placing the MP3 to be played in that area, just like in Figure-3.

Below, I provide the reasons for the first area to be modified, explaining why the green-highlighted portion circled in Figure-2 is redundant: think back to what I mentioned earlier _When I click "Albums", then click "English Grammar in Use", see below picture Figure-1:_ , when I click "English Grammar in Use", I already know which album I want to enter.  Personally, I feel there's no need to include images in Figure-2; it could be without images. However, if you insist on including images in Figure-2 and it's not too much trouble for you, you could place the images to the left of each MP3 file to be played, similar to what's shown in Figure-3 above.

# Second issue 

The second issue concerns the sorting method of the files in Figure-2.

When I practice English listening, I encounter a scenario where I need to start learning from the beginning of an English listening book, or I can only start from the first chapter. It's like playing a game where my character isn't initially strong enough to defeat the ultimate boss. Therefore, I need to gradually practice and improve my skills, starting from the basics. This principle applies to my English listening practice as well. I need to start from the very beginning, such as 1A, 1B, 1C, 2A, 2B, 2C, 3A, and so on. Therefore, the file sorting method on Figure-2 is terrible for me. I expect the files to be sorted starting from 1, then 2, followed by 3, ... ,100, 101,102, 103 ... and so on, just like below Figure-4.

![Figure-4](https://github.com/ShokhrukhbekYuldoshev/Meloplay/assets/50985604/c6763c58-4478-4115-b952-84f97cbd4d73)

And Windows operating system file sorting method see below Figure-5:

![Figure-5](https://github.com/ShokhrukhbekYuldoshev/Meloplay/assets/50985604/020f37a9-2529-461c-9cc8-e56973f39a81)

Of course, the sorting method is optional. I expect it to follow the sorting order shown in Figure-4 and Figure-5. Alternatively, if it's not too much trouble, you could add a sorting feature, but I expect the default to be the sorting order shown in images Figure-4 and Figure-5.

Thank you very much for your efforts. Your application has been very helpful for me in improving my English listening skills.

**Comment by mkzpd** [comment]
# update

I forked the repository, I review the code so I find the reason that I can't see "100A" on the interface at album, because of below code in file  _\lib\src\presentation\pages\album_page.dart_ at line 37, I think it is bug for short time English listen mp3 file that time less than 10 seconds so I comment it.
```
    // remove songs less than 10 seconds long (10,000 milliseconds)
    songs.removeWhere((song) => (song.duration ?? 0) < 10000);
```

And I modify code for modify albums interface layout, and now mp3 file can be sorted by 1A, 1B, 1C, 2A, 2B, 2C, 3A, ... ,100A , 100B, 100C, 101A, 101B, 101C, 102A, 102B, 102C and so on, so now interface layout is below picture:

![album](https://github.com/ShokhrukhbekYuldoshev/Meloplay/assets/50985604/23eb7a00-0069-48fd-a6fe-c3782622c64f)

I have pull requests for the project, I think that the desired functionality for me has been temporarily implemented for now.

Thank you very much for your efforts.

**Comment by ShokhrukhbekYuldoshev** [comment]
✅
